apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: front
        image: eyadrihmi/front_devops:latest
        ports:
        - containerPort: 4200
      - name: back
        image: eyadrihmi/back_devops:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devops-app
spec:
  selector:
    app: devops-app
  ports:
  - name: front
    port: 80
    targetPort: 4200
  - name: back
    port: 8080
    targetPort: 8080
  type: LoadBalancer
